name: Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ DOCKER_PASSWORD }}" | docker login -u "${{ DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ DOCKER_USERNAME }}/react-app .

      - name: Push Docker Image
        run: docker push ${{ DOCKER_USERNAME }}/react-app

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ EC2_HOST }}
          username: ec2-user
          key: ${{ EC2_SSH_KEY }}
          script: |
            docker pull ${{ DOCKER_USERNAME }}/react-app
            docker stop react-container || true
            docker rm react-container || true
            docker run -d -p 80:80 --name react-container ${{ DOCKER_USERNAME }}/react-app